version: '3.4'

services:
  softlinetestproj_postgresql:
     environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Passw0rd
     ports:
      - "35432:5432"
     networks:
      - shared_practice
     volumes:      
      - ~/.docker-conf/postgresql/data/:/var/lib/postgresql/data

  softlinetestproj:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "65048:80"
    networks:
      - shared_practice
networks:
  shared_practice:
    name: practice
    driver: bridge